### ISSUE TITLE
[Bug] function in .h file

### ISSUE THREAD

**Issue by Chihaya-Yuka** [zhiziqxd/zkernel#2]
You cannot write function in .h file,but you do not create any cpp file.
And you are using C++ but you do not create .hpp file.

**Comment by zhiziqxd** [comment]
thank

**Comment by zhiziqxd** [comment]
但是在.h中编写函数是完全合法的

**Comment by zhiziqxd** [comment]
您好，请问您还在吗

**Comment by zhiziqxd** [comment]
已经修改了关于string.h中使用class但是并未使用hpp后缀的bug,感谢您的奉献，祝您生活愉快!
